language: python
python:
    - "2.7"
    - "3.3"
install:
    - pip install -r requirements/ci.txt --use-mirrors
    
services:
    - redis-server
    - memcached

script: nosetests tests --with-cov -v
after_success:
    - coveralls
